### ISSUE TITLE
HSL support

### ISSUE THREAD

**Issue by superhighfives** [sersoft-gmbh/color-components#2]
Super interested in this library—it looks really solid under the hood. Curious if you have any plans to support more formats in future, like HSL, CIELAB (LCH/HCL), etc?

Thanks for making it open source, too. 😊

**Comment by ffried** [comment]
@superhighfives Thanks for your interest!

I can't make any promises as to _when_ new formats will make it into this lib, but it's totally a core thought of this lib.
I'll keep this open to track this!

**Comment by ffried** [comment]
HSL components have finally been added in v1.10.0 (released just now).
I'm closing this, but I've opened #95 and #96 to track two further possible sets of components.
